### ISSUE TITLE
Issues with cobblestone path and other path types

### ISSUE THREAD

**Issue by PrimordialScoop** [PrehistoricKingdom/feedback#113]
Other path types combined with the cobblestone path all seem to break. Tried it with a similarly wide Hexagon path with other paths branching off but did not have the same issue. 
![Cobblestone tears](https://user-images.githubusercontent.com/78051770/109230231-84179280-7792-11eb-85be-0dfa365963f7.png)

**Comment by Dinobob66mya** [comment]
Other paths have this issue as well
