### ISSUE TITLE
Pathfinding with rocks

### ISSUE THREAD

**Issue by PrimordialScoop** [PrehistoricKingdom/feedback#121]
Animals will attempt to move to a certain point on the map that's beneath rocks. They can't get to that point because rocks, so they'll either walk into the rocks without moving, or circle in place endlessly

**Comment by PrehistoricKingdom** [comment]
Animal pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
