### ISSUE TITLE
People Walking through fence

### ISSUE THREAD

**Issue by milkfromalmond** [PrehistoricKingdom/feedback#143]
Placing a path inside a fence allows people to walk through the fence, and they will happily do so
![20210319133101_1](https://user-images.githubusercontent.com/80986076/111839535-2d483900-88b8-11eb-9d2a-439262363f6f.jpg)

**Comment by diddle783** [comment]
+1

**Comment by PrehistoricKingdom** [comment]
Guest pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
