### ISSUE TITLE
I don't know if this is a bug, but it sure is annoying

### ISSUE THREAD

**Issue by CeratoRaptor** [PrehistoricKingdom/feedback#145]
When hatching a creature and bringing it out of the nursery, you cannot change your camera perspective which makes it incredibly hard to place it where you want to. Whenever I try and change my camera perspective, the creature goes back in the hatchery and I have to try again.

**Comment by ByronMckay** [comment]
Are you trying to rotate the camera with right click? As of the alpha launch version this also cancels any current actions like animal placement, we'll be addressing this soon. In the mean time please use the middle mouse button to orbit.
