### ISSUE TITLE
Unable to delete an autosave and new save file park is completely bare bones

### ISSUE THREAD

**Issue by FahimAriqAkbar1997** [PrehistoricKingdom/feedback#152]
I tried to delete an autosave and it wouldn't let me. On top of that, when I tried opening a new park, it was completely empty except for the terrain textures I had previously painted in the autosave I was trying to delete. 
![image](https://user-images.githubusercontent.com/75088794/111841892-a5b8f500-88cc-11eb-9bf1-2b0b3fe83fef.png)

**Comment by CCplays662** [comment]
ive had the same problem, also lacking an entrance point upon loading a new park

**Comment by PrehistoricKingdom** [comment]
This should be fixed with the most recent patch (0.2.2). You might have to revalidate your Steam files though.

I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
