### ISSUE TITLE
Visitors bug out when path underneath is deleted

### ISSUE THREAD

**Issue by Gixy0** [PrehistoricKingdom/feedback#153]
Sometimes when deleting a path with guests on it, theyll stand there forever and never move even when a 
new path is under them.

![20210319170010_1](https://user-images.githubusercontent.com/55748475/111841895-08ae8a00-88d5-11eb-90ff-49883fae93bb.jpg)

**Comment by PrehistoricKingdom** [comment]
Guest pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
