### ISSUE TITLE
Roofs tab disappears from menu,

### ISSUE THREAD

**Issue by Kingcohen** [PrehistoricKingdom/feedback#155]
The roofing tab has disappeared from my menu. 
![image](https://user-images.githubusercontent.com/80987493/111843330-e2024a80-88f8-11eb-9b95-46ede8825a6a.png)

**Comment by ByronMckay** [comment]
This is a known issue we've been trying to track down for a while. Do you have anymore information about how or when it might have happened during gameplay?
