### ISSUE TITLE
Microraptor is not stopping with eating

### ISSUE THREAD

**Issue by diddle783** [PrehistoricKingdom/feedback#156]
My microraptor start eating and did not stopped..i followed it for 40 minutes and then stopped follow him, got out of the aviary, went back 10 minutes later and it was still eating

**Comment by ByronMckay** [comment]
Mini-Aviary animals perform looped animations and find random positions when the camera leaves the area, they aren't true animals with wandering AI. 

When you returned to the aviary the Microraptor likely selected the eating position again at random.
