### ISSUE TITLE
Visitors continue walking along non-existent paths

### ISSUE THREAD

**Issue by CeratoRaptor** [PrehistoricKingdom/feedback#159]
The title says it all.

**Comment by PrehistoricKingdom** [comment]
Visitors currently only calculate their path before they start moving, and do not recalculate while en route. This will be changing soon so that any obstacles/updates/deletions to things in their path will force them to recalculate their path. I will update this issue once that is complete.

**Comment by PrehistoricKingdom** [comment]
Guest pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
