### ISSUE TITLE
New Game (Save/Load) Bug

### ISSUE THREAD

**Issue by Smanduru** [PrehistoricKingdom/feedback#162]
When I start a new park after having already done one on another save, the map loads without the default trees and with the landscape modified like the first save. It looks like the "new" map carries over the changes done to the terrain, without carrying over water, trees, structures and animals. Just the landscape. 

EDIT: after some tests it seems that deleting the save files (from the game menu) and restarting the game gets rid of the landscape changes, but the "new game" map is still empty without the starting trees already placed in it.

**Comment by PrehistoricKingdom** [comment]
This should be fixed with the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
