### ISSUE TITLE
Loading Saves Not Working

### ISSUE THREAD

**Issue by ShadowxPhenix** [PrehistoricKingdom/feedback#165]
I've had this happen twice where if you try to load a save it gets stuck about 50 percent through loading.. If you exit the game.. and restart it then it will let you load your save. but not if you are playing and exit to main menu and try to load.

**Comment by PrehistoricKingdom** [comment]
Freezing/crashing during saves/loads should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
