### ISSUE TITLE
Loading Game?

### ISSUE THREAD

**Issue by Monstyr** [PrehistoricKingdom/feedback#174]
I started a park with 2 trex's and i spent about an hour on the environment. I then accidently closed down the game and i thought i lost my save but i forgot that it auto saves so its fine but then when i try load the park or other parks the loading bar is stuck at a certain point just before halfway and it appears to be like that forever

**Comment by RudiShumpert** [comment]
I get the same error / issue when trying to create the first world.

**Comment by PrehistoricKingdom** [comment]
Freezing/crashing during saves/loads should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
