### ISSUE TITLE
Dinosaurs walking through fences

### ISSUE THREAD

**Issue by JessAndGretel** [PrehistoricKingdom/feedback#175]
Aloha :,D 
Dinosaurs walking through fences. Especially T-Rex through Modern Metal Fence. 
Happily, Dinosaurs aren't walking through rocks and i often hide fences within rocks.

**Comment by PrehistoricKingdom** [comment]
Animal pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
