### ISSUE TITLE
Guests don't follow the path all the way

### ISSUE THREAD

**Issue by superlord9362** [PrehistoricKingdom/feedback#177]
I built a path going to a Nasutoceratops paddock, and the guests will walk half-way there before stopping and turning around.
Image below.
![20210319160112_1](https://user-images.githubusercontent.com/33046398/111850113-96d24280-88cc-11eb-8331-5f9d7743838e.jpg)

**Comment by superlord9362** [comment]
Expanding the path issue, and they walk further down now.

**Comment by PrehistoricKingdom** [comment]
Guest pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
