### ISSUE TITLE
Power issues for some buildings

### ISSUE THREAD

**Issue by CorpJrdM337** [PrehistoricKingdom/feedback#180]
Some buildings, like a family restroom and a Tea-Rex cafe appear to be having issues with not receiving power, though they are literally right next to both a powerplant, and a solar and wind generator too.  However, most buildings appear to be fully powered with no noticeable power issues there.

**Comment by Xul666** [comment]
I can confirm this!
Moving and re-placing the buildings solved that issue immediatly . 
Nevertheless it's an annoyng bug in my opinion
