### ISSUE TITLE
Modular building piece scaling disabled

### ISSUE THREAD

**Issue by AveMeta** [PrehistoricKingdom/feedback#187]
That's the gist of it, scaling seems to function fine for props and modular foliage, but the option is greyed out (or just non-selectable) in the advanced editing menu for wall and roof primitives. Rotate, height change, and free movement are unaffected.

**Comment by ByronMckay** [comment]
Correct. The intended behaviour is that modular scaling is disabled when **outside** of a group that contains grid-bound wall or roof pieces. This is to prevent the group's grid from breaking apart. When outside of a group they can only be rotated horizontally, too. 

If you're editing **inside** a group, however, scaling is totally allowed on every piece. A little tricky, but a necessary technical trade off.
