### ISSUE TITLE
Loading screen to play not working

### ISSUE THREAD

**Issue by davidydave14** [PrehistoricKingdom/feedback#189]
I downloaded the pre Alpha and tried to load the game, 1st time it crashed, the 2nd and on, it was super slow to load, can't even play the game and when I try to exit, it freezes my whole computer so I have to power off and on the computer and the same thing happens, I left the game loading without touching and after an hour, it let me play the only to have the game play be super slow and not even playable, I need help.

**Comment by nikotr1** [comment]
I think i got the same problem

**Comment by HydraRaptor** [comment]
hey, I'm going through this problem as well, but it works perfectly when I'm playing in low quality, though I would like to play in medium quality but I can't because it won't load up.

**Comment by davidydave14** [comment]
The Twitter page of PK said this

"For those having trouble loading into the game, memory usage appears to be causing issues on systems with less than 8GB of RAM. 

We will be looking into solutions that hopefully allow users on lower end machines to have a more optimal experience." So maybe that's our problem
