### ISSUE TITLE
Styracosaurus freeze in one place

### ISSUE THREAD

**Issue by ThesaurusFranx** [PrehistoricKingdom/feedback#192]
Styracosaurus, usually the male ones, sometimes just freeze in one side of the enclosure without doing nothing until they are moved and sometimes it's not enough and I had to terminate the animal and replace it. On the info it's said that they are "wondering"

**Comment by PrehistoricKingdom** [comment]
Animal pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
