### ISSUE TITLE
Dinos Glitching Trough Fences

### ISSUE THREAD

**Issue by deathdodo** [PrehistoricKingdom/feedback#196]
the dinosaurs were able to just walk trough the fences but after i left and reentered the save it was fixed,
this happened on all parks i made

**Comment by PrehistoricKingdom** [comment]
If you have a save file where this is happening, can you please upload it for us?

You can find your save games in C:\Users\<your username>\Saved Games\Prehistoric Kingdom\Saves

Just zip the folder for the save you want to send and upload it here. 

Thanks!
