### ISSUE TITLE
All modular pieces deleted   

### ISSUE THREAD

**Issue by Empire255** [PrehistoricKingdom/feedback#198]
Has anyone placed modular trees, rocks and logs and end up placing to many or put something to high, and wanting to delete one but end up deleting all of them ?? Is anyone else having this problem ??

**Comment by AmericanFarming** [comment]
By default new pieces are placed into a single group. 

If you demolish this group, it will delete all the contents of the group. If you double click the piece and enter Modular Edit mode (it will say Editing Modular Object at top of screen), and THEN click a piece (only that one piece should be highlighted, not the entire group) and delete it, it will only delete that specific piece.

We are considering making it so new pieces do not spawn into a common group, and instead each create their own group, or making it a toggleable option in the lower right menu.

**Comment by Mr4Goosey** [comment]
This sounds like you accidentally selected the entire modular group that your object was part of, rather than just the object you had in mind.
