### ISSUE TITLE
One Rex despawned after trying to rename it.

### ISSUE THREAD

**Issue by sjuanyu** [PrehistoricKingdom/feedback#201]
Tried to rename a Rex, ended up causing it to despawn

**Comment by JamieBurn99** [comment]
What did you name it? I've noticed that calling a Dinosaur with a name beginning with 'M' causes you to go into move mode with that particular dinosaur.

**Comment by sjuanyu** [comment]
> What did you name it? I've noticed that calling a Dinosaur with a name beginning with 'M' causes you to go into move mode with that particular dinosaur.

Tried to name it "Grimlock", though I didn't get to finish renaming it.
