### ISSUE TITLE
Visitors Walking through fence without path touching the fence

### ISSUE THREAD

**Issue by ariefradityo** [PrehistoricKingdom/feedback#202]
Visitors are walking inside the fence and walking on top of rocks, path are only near the fence and even have a significant gap between them.

https://ibb.co/JFKCCqq

**Comment by PrehistoricKingdom** [comment]
Guest pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
