### ISSUE TITLE
Styracosaurus walking into rock

### ISSUE THREAD

**Issue by Catbuns** [PrehistoricKingdom/feedback#203]
Had to take a short video due to the size, but it's completely shown within the video, Styraco gets stuck up against the rocks and continuously walks into the rocks, cannot unstuck itself. 

https://user-images.githubusercontent.com/81010158/111863937-483eaa00-8999-11eb-85ea-00b98df79eea.mp4

**Comment by PrehistoricKingdom** [comment]
Animal pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
