### ISSUE TITLE
freezes when loading into park.

### ISSUE THREAD

**Issue by AlphaWolf27yt** [PrehistoricKingdom/feedback#205]
i load up the alpha version, everything seems fine until i load about 3/4 of the way and will freeze. A few people have been saying its detecting pk as a virus but i deleted my antivirus. Any help?

**Comment by PrehistoricKingdom** [comment]
Freezing/crashing during saves/loads should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
