### ISSUE TITLE
edmonts not moving

### ISSUE THREAD

**Issue by Toughhorizon** [PrehistoricKingdom/feedback#214]
![screenshot-2021-03-20T12-53-26](https://user-images.githubusercontent.com/80991683/111870218-51208300-897b-11eb-8078-3dd2277d55e7.png)
all of the edmonts in this image has been frozen for the past 10 mins, (im not in pause) apart from the one in the water that's on 2 legs, the rest dont move

**Comment by ProOz3x** [comment]
Try to restart your game, got this issue and restart fix it

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
