### ISSUE TITLE
Loading Save, structures deleted

### ISSUE THREAD

**Issue by LeafProductions** [PrehistoricKingdom/feedback#216]
Hey guys! When loading my save, it seems that many groups of rock, structures, and other things got deleted. It's strange because they appear in the load icon, but they aren't there when you load into the game.

**Comment by PrehistoricKingdom** [comment]
Thank you for the report!

Can you please zip the folder for the save in question that exhibits this behavior, and attach it here?
You can find saves in this folder:
C:/Users/<username>/Saved Games/Prehistoric Kingdom/Saves

Thanks!
