### ISSUE TITLE
Dinosaurs Do Not Move after Crash

### ISSUE THREAD

**Issue by Smitty526** [PrehistoricKingdom/feedback#218]
Dinos aren't moving after initial crash, even the new dinos don't move when added.  But the people still do

**Comment by ProOz3x** [comment]
Try to restart your game, that happen to me and I just restarted to fix it

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
