### ISSUE TITLE
Blank map when creating new park

### ISSUE THREAD

**Issue by cutieannie0120** [PrehistoricKingdom/feedback#219]
I used the "Tree Removal" option of Landscaping while testing out some of the functions. I returned to the Menu and noticed that two save files had been created which were not mine. I removed them, then tried to open a new park file which created a blank map (no vegetation or entrance facility on the map). Reloading the game does not fix the issue but reinstalling it does.
![image](https://user-images.githubusercontent.com/81032025/111876508-6e525300-8975-11eb-9e8f-f84cf17af3bc.png)
![screenshot-2021-03-20T11-44-18](https://user-images.githubusercontent.com/81032025/111875947-b02dca00-8972-11eb-8a83-59006a9c5db1.png)

**Comment by PrehistoricKingdom** [comment]
Whoops, that 'main' level is the new game level. So that's why it stopped working after it was deleted. Normally this 'main' level is hidden, so it was a bug that it showed up in the first place. We will fix this.

Thanks for your report!
