### ISSUE TITLE
guests go off path and walk on rocks

### ISSUE THREAD

**Issue by ollygee** [PrehistoricKingdom/feedback#223]
Guests have suddenly started going off the paths and walking on the rocks placed next to it 
![Prehistoric Kingdom 20_03_2021 16_44_43](https://user-images.githubusercontent.com/81012259/111877602-f6e3ea00-899b-11eb-812e-899cf5bcb3ab.png)
![Prehistoric Kingdom 20_03_2021 16_44_56](https://user-images.githubusercontent.com/81012259/111877673-36aad180-899c-11eb-9ef1-e1ea45ad9fae.png)

**Comment by PrehistoricKingdom** [comment]
Guest pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
