### ISSUE TITLE
Park Entrance bug

### ISSUE THREAD

**Issue by CeratoRaptor** [PrehistoricKingdom/feedback#229]
If you select the park entryway and move it elsewhere, suddenly it shows you all the guest assets in game and causes _huge_ fps drops.

![Screenshot (3428)](https://user-images.githubusercontent.com/60859159/111881485-6ab6d000-8965-11eb-9845-81147531d39e.png)
Image for reference

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
