### ISSUE TITLE
Changing Water Depth and Size doesn't update Water Painting

### ISSUE THREAD

**Issue by DinoSteve93** [PrehistoricKingdom/feedback#23]
Changing brush intensity and size while a water painting action is open doesn't update the tool and instead produces undesired effects. For the time being, it can be circumvented by selecting a different water action after changing the brush, and then re-selecting the desired water type.

![image](https://user-images.githubusercontent.com/59333004/106291783-bc3fba00-6254-11eb-8a5d-a4028e30cca3.png)

**Comment by virtushda** [comment]
Should be fixed, awaiting testing.
