### ISSUE TITLE
Tyrannosaurus phases through glass fencing 

### ISSUE THREAD

**Issue by Bastion14** [PrehistoricKingdom/feedback#231]
Tyrannosaurus (brumal) phases through glass fencing through an exhibit without any issue. Tested this with Tyrannosaurus rex three separate times, but not with any other creature. 

Edit- Walking through the fence*

**Comment by Xul666** [comment]
Same issue with ALL fence types. And all T-Rex skins!
![20210319214030_1](https://user-images.githubusercontent.com/81046847/111887919-94f5a580-89d8-11eb-95a8-9144b85b805b.jpg)
![20210319220615_1](https://user-images.githubusercontent.com/81046847/111887920-958e3c00-89d8-11eb-8b3c-f17d7d0a14d1.jpg)

**Comment by Bastion14** [comment]
That happens, although I've seen the issue happen (and main reason I'm reporting) that rex phases through the glass fence by walking through it.
