### ISSUE TITLE
Autosave crashes game during modular build

### ISSUE THREAD

**Issue by Xul666** [PrehistoricKingdom/feedback#232]
If you are in build mode (for a modular building), the game freezes as soon as autosave is executed.

**Comment by PrehistoricKingdom** [comment]
Does the game crash entirely or just freeze for some time? Autosaving can temporarily freeze the game but it should then resume, this can take anywhere from 1 to 30 seconds depending on the complexity of your park. If the game crashes out entirely however then this is definitely an issue.

If it crashes entirely please attach your player.log file to this post, you can find it here:
C:/Users/<username>/AppData/LocalLow/Blue Meridian/Prehistoric Kingdom

**Comment by Xul666** [comment]
The game froze during the autosave. Then after a minute entirely crashed. This happened 2 times yesterday. If it happens again, I'll attach the log file...

**Comment by PrehistoricKingdom** [comment]
Freezing/crashing during saves/loads should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
