### ISSUE TITLE
Visitors are running through the Microraptor cage

### ISSUE THREAD

**Issue by Toastys110** [PrehistoricKingdom/feedback#233]
![screenshot-2021-03-20T21-17-31](https://user-images.githubusercontent.com/80986299/111884411-d595f480-89c1-11eb-8523-27bf2179e21b.png)

**Comment by diddle783** [comment]
same issue here

**Comment by PrehistoricKingdom** [comment]
This has been fixed and will be in the next patch.

Thanks for your report!
