### ISSUE TITLE
Dinosaurs stop walking/animating when reaching steep terrain and when reaching modular buildings

### ISSUE THREAD

**Issue by Raisenhaus** [PrehistoricKingdom/feedback#235]
Dinosaurs seem to get stuck when terrain changes in steepness and when dinosaurs attempt to walk onto modular buildings (I had built a shelter next to a hill that allows for the dinosaurs to walk on the roof of the shelter; screenshot attached). 
![20210320213413_1](https://user-images.githubusercontent.com/81047690/111884798-273f7e80-89c4-11eb-8d08-f60d87d1dcb3.jpg)

**Comment by PrehistoricKingdom** [comment]
Animal pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
