### ISSUE TITLE
dinosaurs stop walking for a couple minutes and then game crashes

### ISSUE THREAD

**Issue by rrextherex** [PrehistoricKingdom/feedback#236]
reloaded my park, and the dinosaurs seemed to not be moving at all. tried to place them in other areas to see if they were stuck, some of them laid down but none of them walked. couple minutes later the game crashed.

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck and freezing/crashing during autosaves should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
