### ISSUE TITLE
Family Restroom freezes the game and Terrain Textures not working

### ISSUE THREAD

**Issue by HydraRaptor** [PrehistoricKingdom/feedback#237]
So while I was trying to build an entrance to my park, I tried to place down a Family Restroom and than suddenly the game froze and I had to turn my pc off and then back on again. Also while I was trying to create an enclosure, the Terrain textures weren't registering, thus I am left with only grass. It says I am painting it but the terrain does not appear.

**Comment by Bastion14** [comment]
I can confirm the terrain painting issue was a common issue for me for a while until randomly it worked on a different save.

**Comment by HydraRaptor** [comment]
Ah, I see. That's definitely something that should be fixed at some point.

**Comment by PrehistoricKingdom** [comment]
Can you post your system specifications here, specifically how much RAM your PC has?

**Comment by HydraRaptor** [comment]
@PrehistoricKingdom Would this be it ?

Installed RAM : 8.00 GB (7.89 usable)

**Comment by PrehistoricKingdom** [comment]
Please see if the most recent patch (0.2.2) solves these issues for you. 

Thanks!
