### ISSUE TITLE
Weird Water Painting Issues

### ISSUE THREAD

**Issue by CeratoRaptor** [PrehistoricKingdom/feedback#239]
When I water paint in certain spots, usually when I come in from the side, some weird thing happens and suddenly the land becomes two dimensional.
![Screenshot (3463)](https://user-images.githubusercontent.com/60859159/111889012-825a7c80-8996-11eb-9f36-f52d2429ca75.png)
![Screenshot (3464)](https://user-images.githubusercontent.com/60859159/111889013-838ba980-8996-11eb-9441-686e11cfa7b4.png)

**Comment by virtushda** [comment]
Is there a consistent way to reproduce this issue? Could you take a video perhaps?
I haven't encountered anything like this in my testing.

Also, how does the smooth brush affect it?

**Comment by CeratoRaptor** [comment]
https://youtu.be/Mrsylk3JvuU
The water bug recreated (I tried it a few times after to see if it was consistent) and me smoothing it.

**Comment by virtushda** [comment]
Thanks for the video!
This looks like it stems from water not reliably being removed when terraforming over it.
I've made multiple enhancements and fixes to this behaviour already, but I'll have to take a closer look.

**Comment by virtushda** [comment]
Also, level is not the correct tool to remove water. While it will (or is supposed to) remove any water that ends up under terrain, it's not designed to affect water in any other way.
