### ISSUE TITLE
Guests walk off path and keep falling into the water

### ISSUE THREAD

**Issue by CeratoRaptor** [PrehistoricKingdom/feedback#240]
The guests will walk off/under paths and it's really annoying, here are some images of it:

![Screenshot (3465)](https://user-images.githubusercontent.com/60859159/111889145-ba15f400-8997-11eb-9fbf-cbc8751a2835.png)

**Comment by PrehistoricKingdom** [comment]
Guest pathfinding has been improved so this should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
