### ISSUE TITLE
Dinosaur legs freak out when moved while the game is paused

### ISSUE THREAD

**Issue by superlord9362** [PrehistoricKingdom/feedback#247]
I moved my Tyrannosaurus while the game was paused to try and get a photo in a better spot, and when I placed him, the legs bugged out. I tested this with my Lambeosaurus and Nasutoceratops as well. They also had minor leg issues, but not as bad as the Tyrannosaurus.
![20210320204727_1](https://user-images.githubusercontent.com/33046398/111893202-40ddc780-89be-11eb-9053-596cc03e9694.jpg)
![20210320205028_1](https://user-images.githubusercontent.com/33046398/111893203-420ef480-89be-11eb-901d-b74ab960e1ae.jpg)
![20210320205044_1](https://user-images.githubusercontent.com/33046398/111893204-420ef480-89be-11eb-8cfa-134666acbd5e.jpg)
![20210320205241_1](https://user-images.githubusercontent.com/33046398/111893205-42a78b00-89be-11eb-854b-250787dfd28f.jpg)

**Comment by PrehistoricKingdom** [comment]
This issue has been fixed and will be in the next patch.

Thanks for your report!
