### ISSUE TITLE
Save files cannot be deleted 

### ISSUE THREAD

**Issue by Racamoni** [PrehistoricKingdom/feedback#248]
Decided to remake a park, tried to delete the original file (and it's autosave), but the option won't work even though I've deleted four auto-saves beforehand without issue.

**Comment by PrehistoricKingdom** [comment]
Is this still an issue or did restarting your game ever fix it? If you delete a save and it doesn't disappear from the list, can you check the actual folder and see if maybe the save was deleted and the list just wasn't updated? You can find the folder here:
C:/Users/your-username/Saved Games/Prehistoric Kingdom/Saves

Deleting a save should only fail if the save folder is open in Windows. We will investigate this further.

Thanks for your report.

**Comment by Racamoni** [comment]
Hello, sorry for the incredibly late response. I checked the save folder and even after deleting the save manually the list doesn’t update, it does however seem to fix itself after restarting the game three-four times. It’s particularly odd because other saves can be deleted just fine up until the last one, which doesn’t disappear immediately.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PrehistoricKingdom** [comment]
The save menu not refreshing should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
