### ISSUE TITLE
Guests fall of modular piece and get stuck underneath

### ISSUE THREAD

**Issue by Jisilra** [PrehistoricKingdom/feedback#252]
I started to test the limits of the quest walking on modular pieces and tried to make stairs. First they didn't want to use them, probably because they were pretty steep like normal staircase. I made a ramp on the other side (a more or less U shaped raised platform) and then when guests started walking up the ramp I tweaked the stairs on the other side to be in the same slope. Guests tried to come down trough them, but fell trough them halfway trough the stairs slope and got stuck underneath. I tried to add a sloped modular piece under the stairs, but it made no difference.
![screenshot-2021-03-20T14-45-46](https://user-images.githubusercontent.com/81069843/111897362-38ba7200-8a28-11eb-9f62-cf5b376eb179.png)

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck and falling through objects should be fixed in the most recent patch (0.2.2). We have also added some stairs to the modular items list. I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
