### ISSUE TITLE
Modular pieces dont load when opening up a saved file

### ISSUE THREAD

**Issue by RedEskimo95** [PrehistoricKingdom/feedback#253]
I created some custom fences in the park and put some bins in, they show on the autosave image on the menu however when it loads in they are missing from the park

**Comment by PrehistoricKingdom** [comment]
Can you please zip the folder for the save in question that exhibits this behavior, and attach it here?
You can find saves in this folder:

C:/Users/your-username/Saved Games/Prehistoric Kingdom/Saves

Thanks!
