### ISSUE TITLE
Parts of terrain refuse to be modified with any terrain tools

### ISSUE THREAD

**Issue by Jisilra** [PrehistoricKingdom/feedback#254]
Found few places in my first habitat that just refused to be modified at all with any terrain tools. I tried to lower ground and they stayed spiked up. I tried leveling and smoothing and even adding water and removing the water, but they just stay on the level they have decided. They also had some water material glittering in them after removing the water, but that was a reported already if I read correctly. Also when I levelled the ground back up there were few black holes near the places of these terrain. Like the mesh would be missing a face or few vertices.
![screenshot-2021-03-20T08-14-45](https://user-images.githubusercontent.com/81069843/111897644-e417f680-8a29-11eb-86fd-bc658a45c067.png)
![screenshot-2021-03-20T08-16-48](https://user-images.githubusercontent.com/81069843/111897646-e7ab7d80-8a29-11eb-842c-ea8d44bcd618.png)

**Comment by sockeyejo** [comment]
I've had this as well.

**Comment by Zenfroid** [comment]
This happens with water painting as well. You can mixsome depths but when you use deep water, they will not merge
![screenshot-2021-03-23T11-15-42](https://user-images.githubusercontent.com/54860864/112170134-32173080-8bc9-11eb-8a88-8b4c20e80d55.png)
