### ISSUE TITLE
Animal Bug

### ISSUE THREAD

**Issue by Warpath17** [PrehistoricKingdom/feedback#257]
When loading my Autosave, my Tarbosaurus bataar disappeared from their enclosure and were replaced by Edmontosaurus. In addition, the animals are static without moving.
https://www.youtube.com/watch?v=_LQ1B6pW9Rs&ab_channel=Warpath

**Comment by PrehistoricKingdom** [comment]
That's an interesting one!

Can you please zip the folder for the save in question that exhibits this behavior, and attach it here?
You can find saves in this folder:
C:/Users/your-username/Saved Games/Prehistoric Kingdom/Saves

Thanks!
