### ISSUE TITLE
dinos not moving

### ISSUE THREAD

**Issue by Toughhorizon** [PrehistoricKingdom/feedback#262]
the dinos in the image have been stood in the exact way for around 5 mins, the t rexes still stand still and roar but apart from that none of them move

![screenshot-2021-03-21T12-54-14](https://user-images.githubusercontent.com/80991683/111905636-8f35a980-8a44-11eb-83cf-2c2222bf49d8.png)

**Comment by JediSpectre117** [comment]
I had this issue after loading my save, Visitors were the same though

**Comment by lZero87** [comment]
same problem by me
