### ISSUE TITLE
Guests not wanting to walk on modular ramp

### ISSUE THREAD

**Issue by Imhungry5462** [PrehistoricKingdom/feedback#267]
I created a modular bridge using 4x2 ramps so that guests could walk over it. However, every time they get close to the bridge they all turn back and head the other way and I have no idea why. I put a path at the other end of the bridge to see if that was the problem but they still didn't like it.

I can provide a save if that would be useful!

![20210321162148_1](https://user-images.githubusercontent.com/38303739/111912555-180f0e00-8a62-11eb-9852-9ec573020894.jpg)

**Comment by PrehistoricKingdom** [comment]
Lowering the ramp an inch or two into the ground may help, though it looks like it's already pretty good.

Have you tried going on 3x speed and seeing if some start going up there after a minute or two? It can take a little bit for changes to the navmesh to propagate through the visitor system, so they will sometimes use paths that you deleted, walk through obstacles you just placed, or not use paths that were just constructed. We will be fixing this soon.

Yes a save would be useful if you don't mind, then I can look at the navmesh and see exactly why they don't like it.

**Comment by Imhungry5462** [comment]
Hello,

I reloaded the save and still no dice, the guests didn't like it. Plus, the ramp is already slightly submerged into the floor, so I don't think that would be an issue.

Anyway, I've got the save here, so have fun with it!

[modular bridge glitch.zip](https://github.com/PrehistoricKingdom/feedback/files/6178462/modular.bridge.glitch.zip)

**Comment by PrehistoricKingdom** [comment]
I loaded your save, the slanted roof piece you are using is slightly too steep for the guests, there is a shallower slanted roof piece (Slanted Roof 4x1) below it that is better suited currently. 

We will be reworking the guest navmesh system to support steeper slopes in the future, but for now stick to the shallow piece. Also the navmesh only regenerates when exiting modular editing mode so be sure to do that once you finish making something for them.

Thanks for your report!
