### ISSUE TITLE
Save deleted all modular objects :C

### ISSUE THREAD

**Issue by Hanna-AlbyTross** [PrehistoricKingdom/feedback#278]
[autosave.zip](https://github.com/PrehistoricKingdom/feedback/files/6178741/autosave.zip)

^ the current file that broke

[first park.zip](https://github.com/PrehistoricKingdom/feedback/files/6178742/first.park.zip)

^ A save that was like 5 or 6 hours of work before

**Comment by PrehistoricKingdom** [comment]
These load just fine for me. Can you try to load them again, then close the game and send us your player.log file?

You can find it here: C:/Users//AppData/LocalLow/Blue Meridian/Prehistoric Kingdom/player.log


This is what I see when I load your autosave park.
![image](https://user-images.githubusercontent.com/77504946/111928029-de9dc900-8a88-11eb-968e-cf39267c5cc1.png)

**Comment by Hanna-AlbyTross** [comment]
Weird, that is exactly how it looked right before it crashed, then next time I opened it was all gone

Now for some reason its crashing when I try to load it again

**Comment by Hanna-AlbyTross** [comment]
God, its crashed like 3 times in a row trying to load "autosave", it crashed everything open on my computer at the same time. I'm gonna try and replace my ingame save with the zipped one tomorrow, It's almost midnight and I'm half awake haha, but if I can't fix it I won't be that upset, I can rebuild it even faster now that I'm better at understanding the building system

**Comment by PrehistoricKingdom** [comment]
How much RAM does your system have? If it is 8GB you could be running low, we are improving RAM usage with the next patch so those using 8GB should be a lot more stable.

**Comment by Hanna-AlbyTross** [comment]
Yes I have 8GB, so that could explain it. I don't mind waiting for the patch then, thank you for helping me <3

**Comment by PrehistoricKingdom** [comment]
We have since released two patches which should lower your RAM consumption significantly. We have also just fixed crashing/freezing during saves in the most recent patch (0.2.2).
 
I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
