### ISSUE TITLE
All Rocks and Modular Items Gone from Habitat.

### ISSUE THREAD

**Issue by vwel5626** [PrehistoricKingdom/feedback#285]
All of the rocks and resized items were removed from the habitats. Its strange kind of like they all disappeared. Also several dinos have stopped moving around, like they are stuck. 
![all rocks gone](https://user-images.githubusercontent.com/81189095/112047956-e8bcd780-8b1b-11eb-8d36-40902f5d3c50.png)

**Comment by PrehistoricKingdom** [comment]
Did this happen upon loading into your save?

Can you please zip the folder for the save in question that exhibits this behavior, and attach it here?
You can find saves in this folder:
C:/Users/_your-username_/Saved Games/Prehistoric Kingdom/Saves

**Comment by vwel5626** [comment]
[test park.zip](https://github.com/PrehistoricKingdom/feedback/files/6185968/test.park.zip)

**Comment by vwel5626** [comment]
So I kind of messed up and did a bunch of work on the park then did not save. The items that disappeared did so after zooming out then zooming back in those items were not in this save because I put them in later. The bug with the dinos definitely happens when I load in and they stay that way. Sorry about not getting the right save cause I started another park will be better in the future,
