### ISSUE TITLE
Entire Park Crashed

### ISSUE THREAD

**Issue by vwel5626** [PrehistoricKingdom/feedback#286]
So while objects were disappearing it seems my entire park has crashed. None of the dinos are moving guests wont enter the park. I will try to start another park to see if this issue happens on that one.

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck and the game crashing/freezing during autosaves should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
