### ISSUE TITLE
Selecting modular building pieces hard when building a complex structure with overlapping pieces

### ISSUE THREAD

**Issue by Jisilra** [PrehistoricKingdom/feedback#295]
When building a more complex building selecting different pieces from it to move is sometimes very hard or occasionally even impossible without saving the game exiting it and reloading the game from the save.

![screenshot-2021-03-23T22-43-36](https://user-images.githubusercontent.com/81069843/112219044-29584600-8c2d-11eb-94db-eb58e8fb109f.png)
I was building this and many times when I for example tried to click on a concrete wall piece near the windows it either didn't select any piece, selected a building piece from the other side of the building, a nearby building piece, or multiple ones or in some cases a building piece that wasn't even adjacent or contacting the one I tried to select.

Many times the only option was to select a huge portion of the building, move it further away from the main structure, copy the pieces that needed to stay in place, move those back to the building, then go to the part I moved in the first place and delete all the other pieces I didn´t need to relocate and then move the rest back to the building to their right places.

And I did move the whole building away from the Tea-Rex Cafe while I was building, because that building inside the modular structure made it even harder to click on any building pieces.

It seemed that just after reloading the game the selecting tool worked a bit better. There were multiple times I couldn't select a piece at all, and after a save and reload I could select it with first click.

**Comment by Jisilra** [comment]
![Selecting_modular_pieces_problem](https://user-images.githubusercontent.com/81069843/112544557-ce0a8d00-8dbf-11eb-84f6-1447e72a1402.JPG)
Here is an example. I was in a process of copy pasting the supporting beam and two pillars to support the whole walkway. Half way trough it just stopped letting me select two of the three pieces. It keeps on selecting nothing or some other piece nearby. The pillar from the back you could select all the time.
Only way I could get those pieces to be selected again to be copied to the next place was dragging a box around them all and then removing all glass pieces one by one from the selection.

**Comment by Xul666** [comment]
Can confirm this!
And not only for "complex" buildings, but also for very simple structures...
I build a small "fence" made of 4 post and 2 ropes - and it was no longer possible to click on one of these parts later on!
No matter from which camera angle.
Only after saving and reloading, I was able to select every single part immediately without any problems...
