### ISSUE TITLE
Game Crashes when loading saves

### ISSUE THREAD

**Issue by Dakotaraptors** [PrehistoricKingdom/feedback#296]
When i try loading my save files, continuing or starting a new game, it crashes on the loading screen.

**Comment by HydraRaptor** [comment]
Are you still having this problem ?

**Comment by PrehistoricKingdom** [comment]
Crashing/freezing during saves/load should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
