### ISSUE TITLE
I can put objects out buildable area.

### ISSUE THREAD

**Issue by WBIgel** [PrehistoricKingdom/feedback#297]
I can put objects out buildable area. Here two pics, I markd the "flying" rock. Plus on the first pic are one rock and two large strawbeds. But I can't put out of area animnals or buildings. (restroom or nursery)
Sorry for my bad English.

![20210323232853_1](https://user-images.githubusercontent.com/81268439/112228433-953cad80-8c31-11eb-9deb-9af9b033a91e.jpg)
![20210323232905_1](https://user-images.githubusercontent.com/81268439/112228437-966dda80-8c31-11eb-8e82-c739304b95f2.jpg)

**Comment by PrehistoricKingdom** [comment]
We are aware you can place modular items outside the building area. We have not decided yet if we want to prohibit this or allow it, as it could be fun to let players build in the background scenery. For now though I will be closing this issue.

Thanks for your report!
