### ISSUE TITLE
Park crashed upon trying to save

### ISSUE THREAD

**Issue by 9headedhydra** [PrehistoricKingdom/feedback#299]
I loaded a save and when I got into game I found none of my dinosaurs were moving. I tried to save the game in order to try reloading it and see if that fixed it. The game then crashed and i was forced to return to desktop.

**Comment by PrehistoricKingdom** [comment]
Freezing/crashing while saving and AI agents getting stuck should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
