### ISSUE TITLE
Animals don't move

### ISSUE THREAD

**Issue by tyrannossenpai** [PrehistoricKingdom/feedback#300]

**Comment by tyrannossenpai** [comment]
It is just after the new update dropped and as soon as I did, none of the animals I had in the park began walking or running. They occasionally roar and lay down, but they don't move from point a to b. I tried moving them to see if it would do anything, but it didn't work. Next I tried closing and then opening the game again, but they still don't move.

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
