### ISSUE TITLE
Screen tearing with fps cap 

### ISSUE THREAD

**Issue by JamieBurn99** [PrehistoricKingdom/feedback#301]
Screen tearing only stops when fps is set to unlimited.

**Comment by PrehistoricKingdom** [comment]
We changed the FPS limiter to be dependent on the monitor refresh rate in the most recent patch (0.2.2), this should hopefully eliminate screen tearing when using the FPS limiter.
I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
