### ISSUE TITLE
Game+Steam crashed on loading screen

### ISSUE THREAD

**Issue by MegalexMaster** [PrehistoricKingdom/feedback#302]
Selected 'New Game', loading bar got half way, before crash handler popped up and the game closed itself. On top of this the steam client also crashed.

**Comment by PrehistoricKingdom** [comment]
We have just released a patch (0.2.2) which should hopefully solve this issue. I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!

**Comment by MegalexMaster** [comment]
With the new update, loading bar now goes just over half way before crashing (just before the little arms of the t-rex for reference), steam client does not crash this time.
