### ISSUE TITLE
Terrafoaming issue

### ISSUE THREAD

**Issue by BionicleWhale** [PrehistoricKingdom/feedback#307]
I can't terrafoam in this location especially water I place down. I am trying to make an island but so far this is what I am having issues with
![screenshot-2021-03-24T18-55-38](https://user-images.githubusercontent.com/81334518/112394458-20ba4b00-8cd3-11eb-9ddf-ee2152559b0b.png)

**Comment by virtushda** [comment]
The workaround for this issue at the moment, is to raise the problem area up a bunch, then you can push it back down

**Comment by BionicleWhale** [comment]
Oh okay thank you!
