### ISSUE TITLE
Mostly frozen in place

### ISSUE THREAD

**Issue by CorpJrdM337** [PrehistoricKingdom/feedback#308]
I jumped back into my latest save to checkout the updated features from update 0.2.1.  However, all of my animals seem to be more or less frozen in their place, and occasionally performing their roars and what I assume are their new social vocals.  Aside from that, they are literally all frozen in their tracks, even after I manually pick them up and move them to a new spot, they will simply just stand there and be idle, or lay down for a few seconds, then stand up again and remain idle.

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
