### ISSUE TITLE
Can't place mini Aviary

### ISSUE THREAD

**Issue by DiligentDilophosaurus** [PrehistoricKingdom/feedback#311]
I do not know exactly what caused this, but whenever I go to place a mini aviary it remains blue indicating the location as a valid placement. (Even when clipping into other objects) But as soon as I click to confirm the placement it becomes highlighted in red indicating an invalid placement. (This happens even if I attempt to place the aviary in an empty flat field.)

https://user-images.githubusercontent.com/81397444/112564738-33578180-8db2-11eb-892b-daab8b53e196.mp4

**Comment by Xul666** [comment]
It looks (on the screenshot) like the aviary is "inside" an enclosure....
Could be that it is not possible to place it then?!
