### ISSUE TITLE
Autosave locking up the game

### ISSUE THREAD

**Issue by litnin** [PrehistoricKingdom/feedback#313]
Autosave has started locking my game up. It saves the game ok but it just locks up and i have to hard close the game and restart. It was working fine before the patch.

**Comment by litnin** [comment]
Created a new game from scratch and its working fine now. Must have just been that save file.

**Comment by HydraRaptor** [comment]
I know I'm experiencing that issue as well, every time I open up one of my old saves, it freezes the game but when I click on New Game, it works. What's up with that ?

**Comment by Xul666** [comment]
Yesterday I had no problems at all.
Today I continued to expand my park - then it was autosaved and the game froze. I could only quit it via the task manager. Since then I can no longer load any saved park. Either the game crashes already while loading or it comes to the situation with the "immobile dinos" and no guests appear ! (see #277). 
A new map can be started without problems, but no more any saved game.

**Comment by litnin** [comment]
Well it would now seem that my file is working again. Very wierd indeed. I did nothing to it, just opened it up again, waited for the autosave, it worked, and its been working fine since.

**Comment by Xul666** [comment]
I tried loading my save games for 2 hours without success!
Sometimes it worked, sometimes not...
It seems that the game is not initialized correctly after closing one park and loading another. 
Sometimes it helps to open an empty map, go back to start manu and load a sve game. But not always.
Renaming the "navmesh.data" into "nav2.data" has no effect in these cases.
The Autosave process still seems to be the trigger for most of this issues...

**Comment by CandiceTheCanuck** [comment]
I am having this issue as well, as soon as autosave starts it just does nothing, had to close out completely. This was on a park I started before update went out. I will have to see how starting a brand new park does and if the problem continues.

**Comment by litnin** [comment]
Defs some sort of major bug. My original file from the start of the Alpha sometimes works, but mostly does not work. I load it up, Dino's don't move and no visitors, but i can build away. The autosave locks it up and so does manual save. Strange thing is that it saves the game, but i have to hard shut down the game and restart to continue.

**Comment by PrehistoricKingdom** [comment]
Freezing while saving and AI agents getting stuck should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
