### ISSUE TITLE
dinosaurs stop moving completely, even after reloading the game multiple times

### ISSUE THREAD

**Issue by rrextherex** [PrehistoricKingdom/feedback#321]
i was having a fun time playing, then, i reloaded back into the game the next day, and none of the dinosaurs would move at all, even after i reloaded the game multiple times, added new dinos, changed the terrain, removed fences, terminated dinos, moved them, nothing seems to work, hoping this issue gets fixed soon.

**Comment by PrehistoricKingdom** [comment]
Freezing while saving and AI agents getting stuck should be fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
