### ISSUE TITLE
my trees, guests and buildings have all disappeared 

### ISSUE THREAD

**Issue by dobbybouglas** [PrehistoricKingdom/feedback#325]
I was building a lot of extra bridges and all sorts of buildings and when I turned to face my park (after a hour or 2 of not paying attention to much of anything else other then this bridge i was working on) i noticed all my trees that were painted in were gone and all my buildings that i have placed (tea rex, bathrooms, creations lab etc.) had disappeared. also I've been having issues since the update with auto saving crashing my program. I didn't have any issues with this before the first patch and now its gotten so bad my stream takes bets on how many times its gonna happen in a night. I know my game is gonna crash when my dinosaurs stop moving in their entirety, and my guests will not enter the park. its really odd. 

![20210328174929_1](https://user-images.githubusercontent.com/81536223/112769456-13f96800-8fef-11eb-93b8-09a090026b7c.jpg)
![20210328174940_1](https://user-images.githubusercontent.com/81536223/112769459-15c32b80-8fef-11eb-8e88-ecf21a3a4ec4.jpg)

**Comment by PrehistoricKingdom** [comment]
AI agents getting stuck and freezing/crashing during autosave should be fixed in the most recent patch (0.2.2). Please let me know if you encounter this issue again after you update.
