### ISSUE TITLE
Bug causes 'new game' to generate no foliage.

### ISSUE THREAD

**Issue by Madebyhazy** [PrehistoricKingdom/feedback#330]
Hello fellow PK'er!

So I was playing a bit with terrain etc., to see how things looked like. I was unsatisfied with my previous build so I decided to create a new game. the game, once loaded, didn't generate any foliage like it normally does, instead it generated the exact same terraforming I did on my previous safe file. Note: I didn't remove the foliage myself on that previous safe file. Click the link for the screenshot: https://imgur.com/I9WkDko

Cheers!

Hazy

**Comment by PrehistoricKingdom** [comment]
This should be fixed with the most recent patch (0.2.2). You might need to validate your Steam files though.

I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!

**Comment by Madebyhazy** [comment]
thank you <3
