### ISSUE TITLE
Modular pieces disappear after game crash

### ISSUE THREAD

**Issue by madmosasaurus** [PrehistoricKingdom/feedback#338]
Buildings like domes containing many modular pieces are completed using copy/paste and then the file is saved correctly. If the game crashes with the same file open (either directly or hours later) and the save file is opened again after the restart, the buildings are still there but are missing random modular pieces.

If I just exit the game and then reload the save files, modular pieces do not disappear.

**Comment by Xul666** [comment]
Can confir this. But not only when game crashes! 
I have finished the game normally. After a few hours I loaded the score and a bridge including decoration was completely gone! Also in the autosave. I thought I had accidentally deleted it and wanted to build it again. But all the building elements (wooden planks, ropes, rocks) that I had used for the object were also not present in the menu with the modular objects! 
So I reloaded the game 2x more and suddenly the bridge was there again.
It seems that some modular objects are not loaded at the start of the game and all objects that were built from them are then of course not visible, although the structure still exists.
