### ISSUE TITLE
  Styracosaurus makes splashing walking noise even when it's going over a river on a makeshift bridge

### ISSUE THREAD

**Issue by Jisilra** [PrehistoricKingdom/feedback#343]
![screenshot-2021-04-07T22-38-06](https://user-images.githubusercontent.com/81069843/113924528-930e4d80-97f2-11eb-85a9-3a82c1ea4cbb.png)

Walking sound is the same like it would be wading trough water.

**Comment by Xul666** [comment]
Can confirm this. I built a platform of concrete tiles nearby a pond. When a dino walks over the tiles you you can hear the sound as if it would wading through the water.
