### ISSUE TITLE
Another Terrafoaming bug??

### ISSUE THREAD

**Issue by BionicleWhale** [PrehistoricKingdom/feedback#346]
I can't raise the mountain any higher than this is this supposed to be like this??? or will devs be working on it?
![screenshot-2021-04-07T16-41-04](https://user-images.githubusercontent.com/81334518/113931116-18c4d580-97c0-11eb-82b5-5db6c581b7bf.png)

**Comment by virtushda** [comment]
This is the intended behaviour for the time being.
