### ISSUE TITLE
Speed selection breaks with pause + screenshot tool

### ISSUE THREAD

**Issue by Jisilra** [PrehistoricKingdom/feedback#347]
How to replicate:

When you are in 3x speed
- Pause the game
- Open up in game screenshot tool
- Close the in game screenshot tool
- Unpause the game and all the animals will move in 1x speed. They will return to 3x speed only after you've gone first back to 1x speed

**Comment by Xul666** [comment]
not only the screenshot tool. Any tool stops the 3x speed. When you return to the game it always runs in normal speed again. But the 3 arrows in the interface (buttom right corner) are still there by mistake - and you might think you are still in 3x speed.
