### ISSUE TITLE
Plants stick through prefab structure floors

### ISSUE THREAD

**Issue by superlord9362** [PrehistoricKingdom/feedback#359]
The default plants stick through the ground of the prefab structures.
![20211206143620_1](https://user-images.githubusercontent.com/33046398/144934266-6882228d-8d72-4ce3-b23a-cd89d870c71d.jpg)
![20211206143512_1](https://user-images.githubusercontent.com/33046398/144934268-7ec24665-0621-4060-9d90-ac99873ad31f.jpg)

**Comment by PrehistoricKingdom** [comment]
Thanks for your report!

This is a known issue and will be fixed in a future patch. For now you can paint a non-grass texture under the building to remove the grass.
