### ISSUE TITLE
Screen locked

### ISSUE THREAD

**Issue by Saurillian** [PrehistoricKingdom/feedback#361]
When I launch the game initially it runs fine, however once a new game loads I get a screen that looks like this, which is frozen, and I have to use task manager to close the game. Tried 3 times, and all 3 times I got this screen
![Screenshot (80)](https://user-images.githubusercontent.com/95659047/144935016-c5e87f5d-8bf7-400d-87dd-b10831921b98.png)
.

**Comment by PrehistoricKingdom** [comment]
Thank you for your report!

Please attach your player.log file here (you may need to zip it first)

You can find it here: C:/Users/_your-username_/AppData/LocalLow/Blue Meridian/Prehistoric Kingdom/player.log
