### ISSUE TITLE
Dinos "shaking" when they walk

### ISSUE THREAD

**Issue by C-IddtheKid** [PrehistoricKingdom/feedback#366]
https://user-images.githubusercontent.com/95665650/144954664-e7e2d87a-5d4a-4cbf-9103-2240acbd2d80.mp4

The Dinos shake when they walk. Not sure why and not sure whether it is a bug or just having to do with my computer.

**Comment by PrehistoricKingdom** [comment]
Thanks for the report, we know of this issue and will hopefully have it fixed in an upcoming patch!
