### ISSUE TITLE
No Dinos Available?

### ISSUE THREAD

**Issue by truedatt1** [PrehistoricKingdom/feedback#367]
I am not full convinced I am not missing something, but I cannot figure out how to research dinos to make them available to place.

**Comment by C-IddtheKid** [comment]
Have you to excavated them and have them made in the nursery?

**Comment by meltedtost** [comment]
@C-IddtheKid how do you excavate them

**Comment by scificb1** [comment]
Click on the Dino symbol on the front page, then click on box that looks like it has a pick in it. Go to those places on the map that show an open lock. Hover and follow instructions.
