### ISSUE TITLE
Dinos Spinning

### ISSUE THREAD

**Issue by C-IddtheKid** [PrehistoricKingdom/feedback#368]
https://user-images.githubusercontent.com/95665650/144956944-6d01537d-805d-4961-855f-ddc688d950fc.mp4

They're doing this now...

**Comment by PrehistoricKingdom** [comment]
We are working on fixing this now, and this should be fixed in a future patch.

In the mean time, selecting the dinosaur and moving them will fix it.

**Comment by Jynnn** [comment]
Same issue with a Proceratops in water 

https://gyazo.com/fdad5537566d8d77bf0be0a73ab8699d
