### ISSUE TITLE
Frame Rate Drops from Guests and Animals

### ISSUE THREAD

**Issue by Anomalocar** [PrehistoricKingdom/feedback#374]
The frame rate remains high and stable when using the building editor.  As guests arrive and animals move about, the frame rate drops and jitters substantially.  Dropping the grass texture down helps some but not much

**Comment by PrehistoricKingdom** [comment]
We have uncovered some performance problems with the guests & animals which should hopefully be greatly reduced in an upcoming patch.

Thanks for your report!
