### ISSUE TITLE
Buggy Reflection from Underneath the Water

### ISSUE THREAD

**Issue by C-IddtheKid** [PrehistoricKingdom/feedback#376]
![image](https://user-images.githubusercontent.com/95665650/144986880-85fe5368-30a4-4308-b29c-1ae82b73df9d.png)

**Comment by Edhelluin** [comment]
![screenshot-2021-12-09T23-17-42](https://user-images.githubusercontent.com/81708643/145678518-e831df98-4e00-415c-aaa0-3c46edea9ea1.png)
![screenshot-2021-12-09T23-17-48](https://user-images.githubusercontent.com/81708643/145678522-50879493-b883-40aa-9ba2-4cb21a7fc5fd.png)
![screenshot-2021-12-09T23-17-59](https://user-images.githubusercontent.com/81708643/145678524-a0f2a5ac-8c09-45f7-9e02-4cbf159723a2.png)

Models and reflection panels are distorted in a couple of ways (look at the position of the eye in the first picture), and sometimes a ghost duplicate is seen (third picture). Beyond that, you can suddenly see through the animal from underwater looking out

**Comment by Jisilra** [comment]
It also mixes up the background sky over the buildings or parts of the dinosaurs that are above the water. Some streaky lines there too.
![Screenshot_underwater_reflection_issue_1](https://user-images.githubusercontent.com/81069843/145730665-24f4976a-1f41-4180-8224-f371d317a141.JPG)
![Screenshot_underwater_reflection_issue_2](https://user-images.githubusercontent.com/81069843/145730667-6773c883-187b-4769-8c97-1c4daf8ecbeb.JPG)
