### ISSUE TITLE
Cannot Destroy the Feeders

### ISSUE THREAD

**Issue by C-IddtheKid** [PrehistoricKingdom/feedback#378]
https://user-images.githubusercontent.com/95665650/144994115-39d29ad9-d972-4174-9f4c-371bc6b3019e.mp4

Cannot Destroy the Feeders with the Demolition Tool, nor can you select the feeders to get rid of them.

**Comment by Zillatamer** [comment]
You have to be able to click the tray to select it, clicking on the food does nothing. Try lowering the ground beneath it, and then seeing if you can click the tray.

**Comment by C-IddtheKid** [comment]
I tried and it works, but I am hoping that they iron this out soon.
