### ISSUE TITLE
Consistent crashes roughly every 10 mins

### ISSUE THREAD

**Issue by NOTMADMADDY** [PrehistoricKingdom/feedback#385]
Crashes seem to happen regardless of activity. 
[DxDiag.txt](https://github.com/PrehistoricKingdom/feedback/files/7670132/DxDiag.txt)

**Comment by NOTMADMADDY** [comment]
[Player.log](https://github.com/PrehistoricKingdom/feedback/files/7670753/Player.log)
[Player-prev.log](https://github.com/PrehistoricKingdom/feedback/files/7670754/Player-prev.log)

**Comment by Edhelluin** [comment]
[Player.log](https://github.com/PrehistoricKingdom/feedback/files/7697199/Player.log)
[terra sierra 2.zip](https://github.com/PrehistoricKingdom/feedback/files/7697204/terra.sierra.2.zip)

Just leaving my issue here too. One of my save files crashes within a few minutes regardless of activity.
