### ISSUE TITLE
Unable to place modular pieces after extended play

### ISSUE THREAD

**Issue by ThePreRex** [PrehistoricKingdom/feedback#387]
https://user-images.githubusercontent.com/95711508/145085208-641419ab-50db-4bb8-955d-080d62110093.mp4

**Comment by DinoSteve93** [comment]
Hi, do you perchance remember if you had enough money to place the piece down?

**Comment by ThePreRex** [comment]
> Hi, do you perchance remember if you had enough money to place the piece down?

No i did not, i realized this after I posted the bug report.
