### ISSUE TITLE
Fences Switching Placement Bug

### ISSUE THREAD

**Issue by hadrosaurhero** [PrehistoricKingdom/feedback#39]
Fences begin to glitch when switching placement mode type in between placing poles.
Replicate, Click on a fence (I think any), have placement mode in linear, place down first pole, before adding 2nd pole change to curved placement mode, place 2nd pole.

**Comment by PrehistoricKingdom** [comment]
Using the hotkey to switch placement mode ('C') will avoid this bug. I will fix the UI button so it doesn't cause this issue anymore.

**Comment by MatthewJolly** [comment]
Fixed, will be in next update.

Thanks for report!
