### ISSUE TITLE
Some signs (for example Swet Tooth shop) too bright in play mode but readable in screenshot mode

### ISSUE THREAD

**Issue by Jisilra** [PrehistoricKingdom/feedback#390]
The lighting of the signs is too bright, and I couldn't find a way to tune them down. The texts in the menus are unreadable in play mode. It is better in the screenshot mode, but not great then either.

**Comment by Jisilra** [comment]
Here in playmode
![Signs_too_bright_2021-12-07](https://user-images.githubusercontent.com/81069843/145102391-22ad4f08-3b48-4729-91a5-8f7c487cce82.jpg

And here in screenshot
![screenshot-2021-12-07T22-36-46](https://user-images.githubusercontent.com/81069843/145102483-b32be4ce-b068-4054-aa4e-6c1bacd795b4.png)
)

**Comment by scificb1** [comment]
heres another too bright sig
![screenshot-2021-12-08T15-19-21](https://user-images.githubusercontent.com/95779209/145286203-88be5442-0a4f-456a-b47d-df5ae4897475.png)
n
