### ISSUE TITLE
Sustenance stuck at 30

### ISSUE THREAD

**Issue by scificb1** [PrehistoricKingdom/feedback#396]
Dino's have the food tray available and a water source but they ignore them. If the setting was set to they could die, they would die. They even lie down in the tray of food sometimes.

**Comment by PrehistoricKingdom** [comment]
Can you upload your save file please? You can find it in C:/Users/_your-username_/Saved Games/Prehistoric Kingdom

Just right-click the folder with your save game, click Send To->Compressed (zipped) Folder, then attach the file it creates here.

Thanks!
