### ISSUE TITLE
Grid is crooked, and certain objects won't delete.

### ISSUE THREAD

**Issue by AzamatShackleford** [PrehistoricKingdom/feedback#397]
When I was building a barn, the grid decided to become crooked, thus making building difficult. When I went to demolish said barn, some pieces, including hay, wouldn't delete. I have reloaded the file, and they still didn't disappear.
![screenshot1](https://user-images.githubusercontent.com/95838769/145333192-64f42c2c-21fd-4ecb-8b76-0d14c59ef166.png)
![screenshot2](https://user-images.githubusercontent.com/95838769/145333194-226f4e1a-e974-491d-8a18-82c7d2e37bb1.png)
.

**Comment by Edhelluin** [comment]
I had the same issue, even the pieces loading into a save from before they were placed. But luckily upon rebooting the game they were gone. 
I have no idea what caused it but in my case I had placed a staircase piece on the grid in the same place, maybe that triggered the textures to remain even when deleted
