### ISSUE TITLE
Mammoths sleeping while graph shows wandering

### ISSUE THREAD

**Issue by scificb1** [PrehistoricKingdom/feedback#401]
All my mammoths never show resting. Always have status of wandering
![20211210150626_1](https://user-images.githubusercontent.com/95779209/145642441-4f0c2dc6-36c1-49df-801a-fdfb1e96630b.jpg)
.

**Comment by PrehistoricKingdom** [comment]
The UI does not currently reflect the actual state of the animal. Should be fixed in next patch.

Thanks for your report!
