### ISSUE TITLE
Status Stuck on "Wandering"

### ISSUE THREAD

**Issue by C-IddtheKid** [PrehistoricKingdom/feedback#408]
![image](https://user-images.githubusercontent.com/95665650/145911963-55762b96-e1b8-4f1c-8009-1942fb12af14.png)

Dinos Drink Water/Eat and the Status stays on Wandering.

**Comment by PrehistoricKingdom** [comment]
The UI does not currently reflect the actual state of the animal. Should be fixed in next patch.

Thanks for your report!
