### ISSUE TITLE
Dinosaurs getting stuck inside of each other

### ISSUE THREAD

**Issue by C-IddtheKid** [PrehistoricKingdom/feedback#409]
![image](https://user-images.githubusercontent.com/95665650/145921308-bcf3c36d-7fa6-4d86-9977-cfaadfa934da.png)

**Comment by PrehistoricKingdom** [comment]
We plan to have local avoidance for the animals in the future (before EA release), but for now they will not collide with each other, and this may sometimes happen as a result.

Thanks for your report!
