### ISSUE TITLE
Camarasaurus eating from flat feeders

### ISSUE THREAD

**Issue by Delimfire** [PrehistoricKingdom/feedback#410]
Ive noticed that the camarasaurus is showing the eating animation of a "Tall Feeder Herbivore" on a "Flat feeder". This should be a bug right?
![20211214192606_1](https://user-images.githubusercontent.com/96141542/146057823-e997088e-2879-4367-8a3f-6766ce3e264a.jpg)
![20211214192553_1](https://user-images.githubusercontent.com/96141542/146057830-4368908f-31a9-4ed6-9289-13859f6d5dd5.jpg)
![20211214192600_1](https://user-images.githubusercontent.com/96141542/146057842-00b984d4-8e78-4a33-a871-22561b8ebc6c.jpg)

**Comment by PrehistoricKingdom** [comment]
Yep! We will look into it.

Thanks for your report!
