### ISSUE TITLE
Low settings low fps high end pc

### ISSUE THREAD

**Issue by XStrmChs** [PrehistoricKingdom/feedback#418]
![Screenshot (794)](https://user-images.githubusercontent.com/81002150/147790050-8316206c-f064-4719-8626-a41cf1a55433.png)

**Comment by Jisilra** [comment]
For me the FPS got even lower after the latest update than it was before. It's 80 FPS on the title screen and gets down to 7 or 8 FPS while it's loading the park and stays there, even though I have just two buildings and no animals or people and the game is paused. Bringing in animals or unpausing the game makes no difference.
I am using high settings though and 4K resolution. I will test later if lowering the settings has any affect at all.
