### ISSUE TITLE
Spinning animal in place

### ISSUE THREAD

**Issue by Matateohead** [PrehistoricKingdom/feedback#431]
some of the animals are spinning in please for no reason

**Comment by Matateohead** [comment]
also they are getting stuck if there is a rock beside the water

**Comment by madmosasaurus** [comment]
After the update today I am getting this issue as well.

**Comment by Jisilra** [comment]
I am getting the same issue. Animals that are first stuck walking in place then start to spin, if you try to modify the terrain near them to smooth a slop or something.

**Comment by in-04** [comment]
Another one with spinning animals
