### ISSUE TITLE
Unable to Place Items Following Demolition

### ISSUE THREAD

**Issue by RPerlman13** [PrehistoricKingdom/feedback#45]
Upon placing a selected structure from the build menu, if the item is still highlighted while clicking into demolition and deleting a planted structure followed by pressing escape to exit demolition mode, will make it impossible to plant the same structure again without clicking a different object within the menu.

**Comment by RPerlman13** [comment]
Expanded: If you have an object selected in the build menu then use escape to exit both the build menu and to cancel placement, reopening the build menu will have the prior object still selected despite not allowing the user to place the selected structure.
![image](https://user-images.githubusercontent.com/78050282/106334853-6234f980-6240-11eb-8330-db2bbf68b6e4.png)

**Comment by DinoSteve93** [comment]
Issue should now be resolved, thanks for reporting.
