### ISSUE TITLE
Shallow Water looks 'Line-y'

### ISSUE THREAD

**Issue by Mr4Goosey** [PrehistoricKingdom/feedback#5]
Shallow water (0.5m) looks 'line-y'. See image. 
![image](https://user-images.githubusercontent.com/27518053/104759947-90064280-5758-11eb-951d-6d6ecf285993.png)

**Comment by DinoSteve93** [comment]
This was slightly improved in the past weeks, but it's still not totally resolved

**Comment by virtushda** [comment]
This issue has been resolved while working on water prepass optimizations.
