### ISSUE TITLE
Messed Up Water Placement

### ISSUE THREAD

**Issue by rawleyjrawley** [PrehistoricKingdom/feedback#53]
After deleting water, then placing water on the same spot, there are jagged patches of land that spawn with it.

![20210129182024_1](https://user-images.githubusercontent.com/78240660/106340570-e2b72280-625f-11eb-82ac-fe699a1d20d9.jpg)

**Comment by Strix1758** [comment]
![image](https://user-images.githubusercontent.com/78242309/106343131-d18c0700-629b-11eb-8550-8fe20d26557b.png)

Experienced the same problem. After deletion, the terrain seems to "save" the location of the waters' edge, which interferes with any new water painted in the same spot.

**Comment by DinoSteve93** [comment]
Closing, duplicate of another water-related issue
