### ISSUE TITLE
Z fighting when overlaying set pieces

### ISSUE THREAD

**Issue by Saxurai** [PrehistoricKingdom/feedback#554]
When putting two construction pieces or items in the same plain, both objects render creating a blinking effect.  I think users will be trying to lay stuff on top of eachother for building effects alot, so solving this will help the creative community alot.

**Comment by virtushda** [comment]
Thank you for your report, but Z-fighting is an inherent issue in 3D rendering, there's no real solution to this except to change the layout of the objects or offset them slightly.
