### ISSUE TITLE
Modular System: Plant Placement Issue

### ISSUE THREAD

**Issue by aadign** [PrehistoricKingdom/feedback#59]
![Screenshot_1](https://user-images.githubusercontent.com/36496482/106347721-c2eb2300-628e-11eb-9642-e8dc8bc89b7e.png)

When clicking plants on the modular system, the ones previously selected stayed highlighted and cannot be clicked back again, making it impossible for the user to be able to place said plant again. This problem occurs when placing bushes and trees using the modular system.

**Comment by DinoSteve93** [comment]
Issue has been fixed, thanks for reporting.
