### ISSUE TITLE
Unity crash on close

### ISSUE THREAD

**Issue by Whiteshark2001** [PrehistoricKingdom/feedback#60]
While playing, I attempted to close the game and was greeted by a crash to desktop, through a unity crash with the PK logo with a red exclamation mark on the popup. Bizarre circumstances, had just placed 11 modular pieces and a mini aviary. Attempts to recreate have been unsuccessful, so unsure if just a chance interaction or something else. 

Player log: 

[Player.log](https://github.com/PrehistoricKingdom/feedback/files/5897695/Player.log)

**Comment by virtushda** [comment]
Log indicates that the crash was produced when the Visitor system tried to shut down.

Will look into this.
Please let us know if the crash happens again. Thanks!

**Comment by PrehistoricKingdom** [comment]
Sorry for the late response, but this should have been fixed in the most recent patch (0.2.2). I will be closing this for now, but if you exhibit the issue again please feel free to reopen it or post a comment here.

Thanks!
