### ISSUE TITLE
Stuck in tutorial - placing the 5 mammoths 

### ISSUE THREAD

**Issue by Kajimine** [PrehistoricKingdom/feedback#609]
I initially created 2 mammoths and placed them in their paddock, then set to create 3 more mammoths and continued with changing the paddock food types and cleaning the dung. Then the tutorial asked me to place 5 mammoths. I placed the remaining 3 I had at the nursery. Unfortunately, the game doesn't seem to "see" the 2 initially placed, and I can't breed more mammoths. I actually can't click on anything else. Unless I'm missing something, I think I may need to restart the tutorial?

**Comment by Killerspy92** [comment]
crazy you posted this the same just happened to me. But i have all 5 in the paddock yet it only saying there 3 in there. also have the same situation were you cant click anything else afterwards.

**Comment by Killerspy92** [comment]
i seemed to of fixed it for myself by saving the same then reloading into it

**Comment by Starbuck1978** [comment]
> i seemed to of fixed it for myself by saving the same then reloading into it

This workaround works. After that, the task can be completed successfully.
