### ISSUE TITLE
To many people NPCs

### ISSUE THREAD

**Issue by CleoraMC** [PrehistoricKingdom/feedback#613]
Current state:
-Costarica map
-Easy mode, not even 3 stars and 450mill+ 
-Only 26 dinos
-Only two spawn buildings, both open
-To many NPCS spawning in, making it super laggy & loss of frames is very bad

Suggestion: 
-Add different npc skins thats just not all white people

**Comment by virtushda** [comment]
We'll tune visitors going forward, and we have the art for various races but just have not implemented it yet.

That said, this github is for bug reports specifically, the discord is a better place for feedback: https://discord.gg/Ny86UVu7
