### ISSUE TITLE
Animals become unclickable after idling a while

### ISSUE THREAD

**Issue by Tlilxuchitl** [PrehistoricKingdom/feedback#617]
Twice in a row I have had to close and relaunch pk during the tutorial because I could not select animals. The only thing I can think that affected this is not touching anything much for a while in order to watch them, and the second time leaving it on the pause screen for ~10-20 minutes. 

Fix is complete program restart.

**Comment by virtushda** [comment]
If you want to just play the game, I'd suggest sandbox mode.
The tutorial is very restrictive because it's trying to guide you through how to play the game.

Thank you!
