### ISSUE TITLE
Tutorial Objective not solving

### ISSUE THREAD

**Issue by juldrew** [PrehistoricKingdom/feedback#675]
"Orbit Around" Mouse2 - I can do whatever, nothing works!

**Comment by Mutator2022** [comment]
Tutorial Objectives / First steps / camera controls: **Orbit Around (Mouse2) not working.**
Move about, Change Camera Height, and Zoom In/Out appear to work fine.

**Comment by juldrew** [comment]
I found it, the objective text is wrong: its not 'mouse2' but 'mouse3/middle mouse button' -that one worked!

**Comment by Mutator2022** [comment]
I have tried the "mouse3" and it does not work for me. Do you think I need to change anything in the mouse settings?

**Comment by juldrew** [comment]
whatever helps. u can set something in controls menue to make ur cam rotating around its own axis. i dont think it depends on your mouse (maybe its mouse2 if it has only 2 buttons at all, i dont know)

**Comment by Mutator2022** [comment]
I remapped the mouse controls to mouse1+mouse2, and that worked.
I tried remapping back to the original configuration but the game does not recognize my mouse3 button.
Also, there are two "Camera rotation" inputs in the Settings under camera control. Could be an issue?
Cheers!
