### ISSUE TITLE
2560x1980 widescreen bug

### ISSUE THREAD

**Issue by Grimnir0** [PrehistoricKingdom/feedback#71]
Widescreen option bugged with shimmers that duplicate items and animals and follow around the screen. Affects in particular rivers and animals, but can seemingly affect most items in the game.

**Comment by DinoSteve93** [comment]
This could be caused by the underwater rendering not adapting to 'exotic' aspect ratios

**Comment by virtushda** [comment]
Fixed!
Thanks for the report!
