### ISSUE TITLE
Water Edge Graphics

### ISSUE THREAD

**Issue by flashybamboo** [PrehistoricKingdom/feedback#722]
This game is going to be great! I haven't had many issues yet but I must say the waters edge looks really blocky, there doesn't seem to be a way of making water appear as it should. The water surface looks great but around the shores the geometry just seems to stop. I've tried setting my graphics to low, med, high, ultra and custom but it looks the same on all levels, and my specs are decent (not amazing but I can run Planet Zoo just fine on high graphics and everything looks beautiful without creating any lag) Hopefully this can be fixed! Thanks

**Comment by virtushda** [comment]
This kind of stuff is great to ask in the Discord. Try using the smooth brush set to a low intensity. The blockiness is a result of the terrain mesh. We'll try to improve how this handles automatically down the road, but for now, the tools are there.
Next patch should also contain a bunch of fixes and improvements for terraforming as well.
