### ISSUE TITLE
Suggestion: Terrain Brush Intensity

### ISSUE THREAD

**Issue by PrimordialScoop** [PrehistoricKingdom/feedback#73]
A few testers have noticed that the terrain brush tends to very quickly overwhelm the terrain beneath it if the mouse is held down for longer than a split second. Even at the lowest intensity, holding the mouse button will quickly paint a solid circle of the new terrain you have selected. To get a lower-intensity mix, you need to spam-click the brush around.

Would it be possible to adjust the intensity so that it reflects the final intensity of the terrain that will be placed within the brush, rather than the rate at which it's painted? For example, if you set the intensity to 10%, no matter how long you hold the button down, the new terrain will not represent more than 10% of the terrain inside the brush.

**Comment by TovesPlays** [comment]
something further on this - Ideally the edges of the terrain brushes would be softer because you often get a hard edge to the terrain paint even when on low density
