### ISSUE TITLE
No dino Interaction?

### ISSUE THREAD

**Issue by Shugercake24** [PrehistoricKingdom/feedback#734]
I'm confused because when I place down viewing areas the people don't use them it's as if its there but invisible to their walking path...

That AND the dinos if you put a big mean carno with a little herbo shouldn't he try to kill/attack? I've seen no interactions between Dino's at all. No breeding No Fighting? Is this  normal?

**Comment by PrehistoricKingdom** [comment]
Hello!

Prehistoric Kingdom has released to Early Access which means not all features are currently implemented or finished. Guest and animal AI are two areas in particular that will be extensively developed and expanded upon over the course of EA.

You can take a look at our public roadmap for more information:
https://trello.com/b/JAp8HMuy/prehistoric-kingdom-public-roadmap

Thanks!
