### ISSUE TITLE
AMD Radeon Support ? 

### ISSUE THREAD

**Issue by DracoAgamicus** [PrehistoricKingdom/feedback#735]
I asked this already a few days Ago but i think I write this here in ? 

Is in the future Updates also planned to put in more Support for AMD Grafic Cards?   

Would be nice to know when this would also make the game still better than its already is. Only want to ask because  this was flowing the entire time in my head.

**Comment by virtushda** [comment]
The game already supports and works on AMD graphics cards.

We'll be releasing a general graphics performance patch soon!
