### ISSUE TITLE
Exhibit Animals vanishing?

### ISSUE THREAD

**Issue by MadamMommet** [PrehistoricKingdom/feedback#738]
My exhibit animals just sort of vanish at random? I noticed some people have them disappear or die after a save is loaded but mine just poof while I am working on other enclosures.

**Comment by Dannisaurus** [comment]
sometimes mine wander into a neighbouring enclosure, you can find them in the animal tab in the bottom left(ish)  corner of the UI. I know this won't fix it but at least you can find them again.

**Comment by Mutator2022** [comment]
My Aviary looses the animals (Archaeopteryx), the assigned environment, and the house and feeder, every time I reload the game.
