### ISSUE TITLE
Research fund is lost

### ISSUE THREAD

**Issue by mffadilah47** [PrehistoricKingdom/feedback#772]
My research fund is suddenly decreased when I re-playing the games. last night I have 6,000 but this morning, it suddenly become 1,000 :(

**Comment by IanYuy** [comment]
Same with me, this happens on loading the save, it drops to around 1k.

**Comment by DinoSteve93** [comment]
Thanks for reporting, I'm currently going through making the saving system more robust, so I'll be taking a look at the issue very soon.
