### ISSUE TITLE
Archaeopteryx unavailable though unlocked

### ISSUE THREAD

**Issue by Wayward-Ghost** [PrehistoricKingdom/feedback#778]
Hello,

I unlocked the archaeopteryx at its excavation site, but it isn't showing in the nursery menu, I can't breed an archaeopteryx (see screenshots)

![Screenshot_excavation_archaeopteryx](https://user-images.githubusercontent.com/105158272/167297580-3a6cedb5-eb4d-4250-82b4-bcc8ebed48b0.jpg)
![Screenshot_no_archaeopteryx](https://user-images.githubusercontent.com/105158272/167297581-0f5ccd9a-dab0-42cb-b3b2-b4610c63e919.jpg)
.

**Comment by stefsterf** [comment]
You need to go to the building tab "Enclosures"(where you can select fences) and open the second tab in the bottom left of your screen called "exhibitions". From there you can build an aviary and breed archaeopteryx and microraptor.

**Comment by Wayward-Ghost** [comment]
Alright, so it wasn't a bug. Thanks a lot !

**Comment by stefsterf** [comment]
No problem!
