### ISSUE TITLE
Aviary is not saved

### ISSUE THREAD

**Issue by stefsterf** [PrehistoricKingdom/feedback#782]
I built my aviary for Archaeopteryx and Microraptor, bred them and edited the scenery of the aviary. Yet when I load the savefile everything including the scenery despawns and I'm left with bare empty branches.

**Comment by jay111112s** [comment]
same its so annoying

**Comment by DinoSteve93** [comment]
I'm fixing this issue today, and it should be patched out with the next update, thanks for reporting!
