### ISSUE TITLE
Mini Aviaries Don't Save

### ISSUE THREAD

**Issue by FinnLFC19** [PrehistoricKingdom/feedback#808]
## Bug Description
The mini aviary environmental settings and dinosaurs (I've only tried this with microraptor) don't save and disappear when you reload the game

## Steps to reproduce the issue
Add dinosaurs/new environmental settings to the mini aviary, save and reload the game

**Comment by DinoSteve93** [comment]
Hi, I've fixed this issue and it should be out in the next patch, thanks for the thorough report! :)
