### ISSUE TITLE
Always crashes on Loading a Parc [With Crash Files]

### ISSUE THREAD

**Issue by CoolerTim** [PrehistoricKingdom/feedback#900]
I was able to play the game well. As of now, the game always crashes when I want to load a park or create a new one.

**Comment by CoolerTim** [comment]
Here are the Crash Files:
[Crashes.zip](https://github.com/PrehistoricKingdom/feedback/files/9700227/Crashes.zip)

**Comment by virtushda** [comment]
Please let me know if this crash is resolved in the latest update.

**Comment by CoolerTim** [comment]
> Please let me know if this crash is resolved in the latest update.

Yes, the game no longer crashes :)
